name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          python -m pytest

      - name: Package application
        run: |
          zip -r application.zip . -x '*.git*' '*.github*' 'venv/*' '*.env*'

      - name: Upload artifact to S3
        uses: aws-actions/upload-s3@v3
        with:
          path: application.zip
          bucket: demo-artifact  # Replace with your S3 bucket name
          key: application-${{ github.sha }}.zip

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::120569639058:role/github-actions-role
          aws-region: ap-south-1

      - name: Deploy to AWS CodeDeploy
        run: |
          aws deploy create-deployment \
            --application-name python-application \
            --deployment-group-name python-application-group \
            --s3-location bucket=demo-artifact,bundleType=zip,key=application-${{ github.sha }}.zip
